import { writable } from "svelte/store";

const data = {
	graduationImages: [
		'./exhibitions/graduation-images/1.webp',
		'./exhibitions/graduation-images/2.webp',
		'./exhibitions/graduation-images/3.webp',
		'./exhibitions/graduation-images/4.webp',
		'./exhibitions/graduation-images/5.webp',
		'./exhibitions/graduation-images/6.webp',
		'./exhibitions/graduation-images/7.webp',
		'./exhibitions/graduation-images/8.webp',
		'./exhibitions/graduation-images/9.webp',
		'./exhibitions/graduation-images/10.webp',
		'./exhibitions/graduation-images/11.webp',
		'./exhibitions/graduation-images/12.webp',
		'./exhibitions/graduation-images/13.webp',
		'./exhibitions/graduation-images/14.webp',
		'./exhibitions/graduation-images/15.webp',
		'./exhibitions/graduation-images/16.webp',
		'./exhibitions/graduation-images/17.webp',
		'./exhibitions/graduation-images/18.webp',
		'./exhibitions/graduation-images/19.webp',
		'./exhibitions/graduation-images/20.webp',
		'./exhibitions/graduation-images/21.webp',
		'./exhibitions/graduation-images/22.webp',
		'./exhibitions/graduation-images/23.webp',
		'./exhibitions/graduation-images/24.webp',
		'./exhibitions/graduation-images/25.webp',
		'./exhibitions/graduation-images/26.webp',
		'./exhibitions/graduation-images/27.webp',
		'./exhibitions/graduation-images/28.webp',
		'./exhibitions/graduation-images/29.webp',
		'./exhibitions/graduation-images/30.webp',
		'./exhibitions/graduation-images/31.webp',
		'./exhibitions/graduation-images/32.webp',
		'./exhibitions/graduation-images/33.webp',
		'./exhibitions/graduation-images/34.webp',
		'./exhibitions/graduation-images/35.webp',
		'./exhibitions/graduation-images/36.webp',
		'./exhibitions/graduation-images/37.webp',
		'./exhibitions/graduation-images/38.webp',
		'./exhibitions/graduation-images/39.webp',
		'./exhibitions/graduation-images/40.webp',
		'./exhibitions/graduation-images/41.webp',
		'./exhibitions/graduation-images/42.webp',
		'./exhibitions/graduation-images/43.webp',
		'./exhibitions/graduation-images/44.webp',
		'./exhibitions/graduation-images/45.webp',
		'./exhibitions/graduation-images/46.webp',
		'./exhibitions/graduation-images/47.webp',
		'./exhibitions/graduation-images/48.webp',
		'./exhibitions/graduation-images/49.webp'
	],
	graduationPressImages: [
		'./exhibitions/graduation-press-images/1.webp',
		'./exhibitions/graduation-press-images/2.webp',
		'./exhibitions/graduation-press-images/3.webp',
		'./exhibitions/graduation-press-images/4.webp',
		'./exhibitions/graduation-press-images/5.webp',
		'./exhibitions/graduation-press-images/6.webp',
		'./exhibitions/graduation-press-images/7.webp',
		'./exhibitions/graduation-press-images/8.webp',
		'./exhibitions/graduation-press-images/9.webp',
		'./exhibitions/graduation-press-images/10.webp',
		'./exhibitions/graduation-press-images/11.webp',
		'./exhibitions/graduation-press-images/12.webp',
		'./exhibitions/graduation-press-images/13.webp',
		'./exhibitions/graduation-press-images/14.webp',
		'./exhibitions/graduation-press-images/15.webp',
		'./exhibitions/graduation-press-images/16.webp',
		'./exhibitions/graduation-press-images/17.webp',
		'./exhibitions/graduation-press-images/18.webp',
		'./exhibitions/graduation-press-images/19.webp',
		'./exhibitions/graduation-press-images/20.webp',
		'./exhibitions/graduation-press-images/21.webp',
		'./exhibitions/graduation-press-images/22.webp',
		'./exhibitions/graduation-press-images/23.webp',
		'./exhibitions/graduation-press-images/24.webp',
	]
};


const exhibitions = writable(data)

export default exhibitions
