import { writable } from "svelte/store";

const data = {
	graduationImages: [
		'./exhibitions/graduation-images/0-image65.jpg',
		'./exhibitions/graduation-images/1-image64.jpg',
		'./exhibitions/graduation-images/2-image44.jpg',
		'./exhibitions/graduation-images/3-image58.jpg',
		'./exhibitions/graduation-images/4-image53.jpg',
		'./exhibitions/graduation-images/5-image42.jpg',
		'./exhibitions/graduation-images/6-image41.jpg',
		'./exhibitions/graduation-images/7-image66.jpg',
		'./exhibitions/graduation-images/8-image74.jpg',
		'./exhibitions/graduation-images/9-image001.jpg',
		'./exhibitions/graduation-images/10-image002.jpg',
		'./exhibitions/graduation-images/11-image003.jpg',
		'./exhibitions/graduation-images/12-image024.jpg',
		'./exhibitions/graduation-images/13-image004.jpg',
		'./exhibitions/graduation-images/14-image59.jpg',
		'./exhibitions/graduation-images/15-image007.jpg',
		'./exhibitions/graduation-images/16-image008.jpg',
		'./exhibitions/graduation-images/17-image009.jpg',
		'./exhibitions/graduation-images/18-image010.jpg',
		'./exhibitions/graduation-images/19-image011.jpg',
		'./exhibitions/graduation-images/20-image012.jpg',
		'./exhibitions/graduation-images/21-image014.jpg',
		'./exhibitions/graduation-images/22-image015.jpg',
		'./exhibitions/graduation-images/23-image016.jpg',
		'./exhibitions/graduation-images/24-image017.jpg',
		'./exhibitions/graduation-images/25-image020.jpg',
		'./exhibitions/graduation-images/26-image025.jpg',
		'./exhibitions/graduation-images/27-image028.jpg',
		'./exhibitions/graduation-images/28-image.jpg',
		'./exhibitions/graduation-images/29-image030.jpg',
		'./exhibitions/graduation-images/30-image034.jpg',
		'./exhibitions/graduation-images/31-image036.jpg',
		'./exhibitions/graduation-images/32-image39.jpg',
		'./exhibitions/graduation-images/33-image40.jpg',
		'./exhibitions/graduation-images/34-image54.jpg',
		'./exhibitions/graduation-images/35-image45.jpg',
		'./exhibitions/graduation-images/36-image46.jpg',
		'./exhibitions/graduation-images/37-image49.jpg',
		'./exhibitions/graduation-images/38-image51.jpg',
		'./exhibitions/graduation-images/39-image52.jpg',
		'./exhibitions/graduation-images/40-image55.jpg',
		'./exhibitions/graduation-images/41-image56.jpg',
		'./exhibitions/graduation-images/42-image57.jpg',
		'./exhibitions/graduation-images/43-image60.jpg',
		'./exhibitions/graduation-images/44-image61.jpg',
		'./exhibitions/graduation-images/45-image71.jpg',
		'./exhibitions/graduation-images/46-image72.jpg',
		'./exhibitions/graduation-images/47-image.JPG',
		'./exhibitions/graduation-images/48-image.JPG'
	],
	graduationPressImages: [
		'./exhibitions/graduation-press-images/0-1.jpg',
		'./exhibitions/graduation-press-images/1-A.TAREK-0018.jpg',
		'./exhibitions/graduation-press-images/2-3.jpg',
		'./exhibitions/graduation-press-images/3-_MG_9126.jpg',
		'./exhibitions/graduation-press-images/4-9.jpg',
		'./exhibitions/graduation-press-images/5-R0025373.jpg',
		'./exhibitions/graduation-press-images/6-10.jpg',
		'./exhibitions/graduation-press-images/7-A.TAREK-0103.jpg',
		'./exhibitions/graduation-press-images/8-A.TAREK-0120.jpg',
		'./exhibitions/graduation-press-images/9-2.jpg',
		'./exhibitions/graduation-press-images/10-MG_8747.jpg',
		'./exhibitions/graduation-press-images/11-24.jpg',
		'./exhibitions/graduation-press-images/12-32.jpg',
		'./exhibitions/graduation-press-images/13-TAREK979.jpg',
		'./exhibitions/graduation-press-images/14-A.TAREK-0065.jpg',
		'./exhibitions/graduation-press-images/15-z1.jpg',
		'./exhibitions/graduation-press-images/16-A.TAREK-0071.jpg',
		'./exhibitions/graduation-press-images/17-A.TAREK-0075.jpg',
		'./exhibitions/graduation-press-images/18-A.TAREK-0097.jpg',
		'./exhibitions/graduation-press-images/19-A.TAREK-0098.jpg',
		'./exhibitions/graduation-press-images/20-A.TAREK-0106.jpg',
		'./exhibitions/graduation-press-images/21-TAREK962+copy.jpg',
		'./exhibitions/graduation-press-images/22-R0024812-2.jpg',
		'./exhibitions/graduation-press-images/23-A.TAREK-0099.jpg'
	]
};


const exhibitions = writable(data)

export default exhibitions
